#
# Message in A bottle Docker Compose file
#

version: "3.6"

services:

  message_broker_rabmq:
    #
    # Message Broker Rabbit MQ
    #
    image: library/rabbitmq:3.8.5-management
    ports:
      - "15672:15672" # Management URL (only for utility)
    env_file:
      - env_file
    healthcheck:
      # basic health check
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      # this is only for development purpose
      - "5342:5342"
    env_file:
      - env_file

  mib_users:
    <<: &mib_users
      # Building the image
      image: "mib-users:latest"
      build:
        context: .
        dockerfile: Dockerfile 

    ports:
     - "5000:5000"
    env_file:
      - env_file
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
      - migrations

  migrations:
    #
    # this service is used to apply migrations on db
    #
    <<: *mib_users
    command: flask db upgrade
    env_file:
      - env_file
    environment:
      - POSTGRES_HOST=db
    restart: on-failure

# Declaring all volumes
volumes:
  pgdata: # for maintaing db data
