#
# Message in A bottle Docker Compose file
#

version: "3.6"

services:
  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      # this is only for development purpose
      - "5342:5342"
    env_file:
      - env_file

  mib_users:
    <<: &mib_users
      # Building the image
      image: "mib-users:latest"
      build:
        context: .
        dockerfile: Dockerfile 
  
    ports:
     - "5000:5000"
    env_file:
      - env_file
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
      - migrations
  users-bg:
      depends_on:
        - celery
        - lottery
        - db
        - migrations
      build: .
      env_file:
        - env_file
      environment:
        - POSTGRES_HOST=db
        - REDIS_HOST=redis
      command: python3 -u subscribers.py
      links:
        - redis

  redis:
    image: "redis:alpine"
    container_name: rd01
    command: --port 6379
    ports:
      - "6379:6379"
  migrations:
    #
    # this service is used to apply migrations on db
    #
    <<: *mib_users
    command: flask db upgrade
    env_file:
      - env_file
    environment:
      - POSTGRES_HOST=db
    restart: on-failure

# Declaring all volumes
volumes:
  pgdata: # for maintaing db data
