openapi: "3.0.1"
info:
  title: Users Service API
  description: Users Microservice of Message in a Bottle Application
  version: "0.1"

servers:
  - url: /

paths:
  /user:
    post:
      summary: Add a new user
      tags:
        - Users
      operationId: mib.resources.users.create_user
      requestBody:
        description: Create a new customer inside microservice app
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        201:
          description: Created
        200:
          description: User already exists
        default:
          description: Error during creation of the user


  /users_list:
    get:
      tags: [Users]
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: search users with the keyword specified
      description: Gets the list of all users
      operationId: mib.resources.users.get_users_list
      responses:
        200:
          description: Return users list
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
        default:
          description: An error occured during retrieving the user


  /user/{user_id}:
    get:
      tags: [ User ]
      description: Get a user by its id
      operationId: mib.resources.users.get_user
      parameters:
        - name: user_id
          description: User Unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Return user
        404:
          description: User not found
        default:
          description: An error occured during retrieving the user

    delete:
      tags: [ User ]
      description: Delete a user by its id
      operationId: mib.resources.users.delete_user
      parameters:
        - name: user_id
          description: User Unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        202:
          description: User deleted
        404:
          description: User not found
        default:
          description: An error occured during the deletion the user

  /user_email/{user_email}:
    get:
      tags: [ User ]
      description: Get a user by its email
      operationId: mib.resources.users.get_user_by_email
      parameters:
        - name: user_email
          description: User Unique Email
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Return user
        404:
          description: User not found
        default:
          description: An error occured during retrieving the user

  /authenticate:
    post:
      summary: Authenticate a user
      tags: [ Users ]
      operationId: mib.resources.auth.authenticate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              x-body-name: auth
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: user@studenti.unipi.it
                password:
                  type: string
                  example: abcd123A
      responses:
        200:
          description: User credentials are correct
          content:
            application/json:
              schema:
                type: object
                properties:
                  authentication:
                    type: string
                    description: "It can be failure or success"
                    default: 'failure'
                  user:
                    $ref: '#/components/schemas/User'

        400:
          description: User credentials are not correct
          content:
            application/json:
              schema:
                type: object
                properties:
                  authentication:
                    type: string
                    description: "It can be failure or success"
                    default: 'failure'
        default:
          description: An error occured during login
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_message:
                    type: string        
components:
  schemas:
    User:
      required:
        - first_name
        - last_name
        - email
        - birthdate
      type: object
      properties:
        first_name:
          type: string
          description: First name of user
          example: Mario
        last_name:
          type: string
          description: Last name of user
          example: Rossi
        nickname:
          type: string
          description: Nickname of user
          example: '_mariorossi_'
        location:
          type: string
          description: Place of user
          example: Pisa
        pfp_path:
          type: string
          description: Path of user profile picture
          example: 'default.png'
        blacklist:
          type: string
          description: List of blacklisted users
          example: '1|2'
        content_filter:
          type: boolean
          description: Flag for content filter of user
          example: false
        lottery_points:
          type: integer
          description: Number of user lottery points
          example: 0
          format: int64
        is_banned:
          type: boolean
          description: Flag indicating if user is banned
          example: false
        email:
          type: string
          description: User email
          example: mario.rossi@example.org
          format: email
        birthdate:
          type: string
          description: User birthdate
          example: '2020-01-01'
          format: date
        phone:
          type: string
          description: User phone number
          example: '+39 3332222384'
          minLength: 10
          maxLength: 25
        password:
          type: string
          description: User password
          example: 'abcd1234'
          minLength: 5
          maxLength: 127
    
    UpdateUser:
      required:
        - email
        - password
        - phone
      type: object
      properties:
        email:
          type: string
          description: Customer email
          example: mario.rossi@example.org
          format: email
        password:
          type: string
          description: Customer password
          example: 'abcd1234'
          minLength: 5
          maxLength: 127
        phone:
          type: string
          description: Customer phone number
          example: '+39 3332222384'
          minLength: 10
          maxLength: 25
