"""empty message

Revision ID: 124a8d5f7051
Revises: 
Create Date: 2021-11-12 13:38:18.031320

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "124a8d5f7051"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Report",
        sa.Column("id_report", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_reported", sa.Integer(), nullable=False),
        sa.Column("id_signaller", sa.Integer(), nullable=False),
        sa.Column("date_of_report", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id_report"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Report")
    # ### end Alembic commands ###
